import { CategoryDetail, Category } from "./types";

export const categories: CategoryDetail[] = [
	{
		category: Category.A,
		name: "A",
		floor: "0",
		price: "50",
		supply: 1,
		startingTokenId: 0,
		type: "Procedural Marble",
	},
	{
		category: Category.B,
		name: "B",
		floor: "0",
		price: "25",
		supply: 2,
		startingTokenId: 1,
		type: "Procedural Marble",
	},
	{
		category: Category.C,
		name: "C",
		floor: "0",
		price: "5",
		supply: 8,
		startingTokenId: 3,
		type: "Procedural Marble",
	},
	{
		category: Category.D,
		name: "D",
		floor: "0",
		price: "3",
		supply: 12,
		startingTokenId: 11,
		type: "Fluid",
	},
	{
		category: Category.E,
		name: "E",
		floor: "1",
		price: "2",
		supply: 16,
		startingTokenId: 23,
		type: "Fluid",
	},
	{
		category: Category.F,
		name: "F",
		floor: "1",
		price: "1",
		supply: 18,
		startingTokenId: 39,
		type: "Fluid",
	},
	{
		category: Category.G,
		name: "G",
		floor: "1",
		price: "0.8",
		supply: 24,
		startingTokenId: 57,
		type: "Stone",
	},
	{
		category: Category.H,
		name: "H",
		floor: "1",
		price: "0.7",
		supply: 32,
		startingTokenId: 81,
		type: "Abstract",
	},
	{
		category: Category.I,
		name: "I",
		floor: "2",
		price: "0.5",
		supply: 32,
		startingTokenId: 113,
		type: "Wood",
	},
	{
		category: Category.J,
		name: "J",
		floor: "2",
		price: "0.2",
		supply: 36,
		startingTokenId: 145,
		type: "Glitch",
	},
	{
		category: Category.K,
		name: "K",
		floor: "2",
		price: "0.1",
		supply: 41,
		startingTokenId: 181,
		type: "Acid",
	},
];
